[package]
name = "slinkylib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internals
schnorrkel = "0.11.4"
rand = "0.8.5"

# Encoding
hex = "0.4.3"
base32 = "0.5.0"
bs58 = "0.5.1"